package:
  name: charge
  version: 'a0.5_dev1'

source:
  git_rev: 'a0.5_dev1'
  git_url: 'https://github.com/Zer0Credibility/charge'

requirements:
  host:
    - python
    - setuptools
    - numpy
    - pandas
    - tqdm
    - scipy
    - statsmodels
    - matplotlib

  run:
    - python

test:
  imports:
    - charge

about:
  home: 'https://github.com/Zer0Credibility/charge'
  license: BSD
  license_file: LICENSE